### ISSUE TITLE
建议在verb/verbatim中使用原样的引号

### ISSUE THREAD

**Issue by WenboSheng** [louisstuart96/lshort-new-zh-cn#3]
代码中的引号显示是 ‘ ’ 的样式，建议改为 ` ' （\char13, \char18），否则还是不清楚哪个键。原版的 lshort 也是这个毛病。

**Comment by louisstuart96** [comment]
啊哈……那个是字体的缘故，cmtt / lmtt 里 \char13 和 \char18 确实长那样。

**Comment by WenboSheng** [comment]
双引号不也是两个 ` 么，symbols 里面建议用 upquote 只更改 verb/verbatim 里面的引号，可以试一下是否兼容。

**Comment by louisstuart96** [comment]
之前理解错了……

我放弃解决这个问题了。用到引号的地方不多，还是 \verb 和 \texttt 混用的（除了 verbatim 环境以及 src\README.md 里提到的 example 环境，代码里极少自己手写 \verb 环境，有些地方甚至因为用到了宏，更没法用 \verb。

我再想想怎么组织吧。
