### ISSUE TITLE
5.3节的图5.1似乎不全

### ISSUE THREAD

**Issue by WenboSheng** [louisstuart96/lshort-new-zh-cn#4]
图5.1的右边和下边似乎不全？似乎是layouts的效果，实在不行直接用 layout 算了。

**Comment by louisstuart96** [comment]
layout 宏包的图没法放在浮动体里。

**Comment by louisstuart96** [comment]
之前有问题是因为 layout 宏包会给双面文档两面各放一个 layout 图，但是浮动体里面换不了页，于是就 bug 了。现在简单作了一个 hack。
