### ISSUE TITLE
第八章 

### ISSUE THREAD

**Issue by xiaoleeza** [louisstuart96/lshort-new-zh-cn#5]
有人给我发邮件，在 ctan 20160523 那一版, 有一处错误  央视 应该修改为 样式

**Comment by xiaoleeza** [comment]
github 里我看已经更正了, 你看看什么时候上传到 ctan

**Comment by louisstuart96** [comment]
囧，改天我把 CTeX-org 下面的那个仓库搞一下更到 CTAN 上吧，这个仓库弃用了。
