### ISSUE TITLE
5.1.4 字体编码一节关于连字符的叙述有误

### ISSUE THREAD

**Issue by zepinglee** [louisstuart96/lshort-new-zh-cn#6]
在英文中很少使用波浪号作为连字符，所以 5.1.4 节中的 “a~b” 用法是错误的，包括 `\textasciitilde` 和 `\textasciitilde`。

https://en.wikipedia.org/wiki/Tilde
> In some languages (though not generally in English)[citation needed], a tilde-like wavy dash may be used as punctuation (instead of an unspaced hyphen or en-dash) between two numbers, to indicate a range rather than subtraction or a hyphenated number (such as a part number or model number). For example, "12~15" means "12 to 15", "~3" means "up to three", and "100~" means "100 and greater". Japanese and other East Asian languages almost always use this convention, but it is often done for clarity in some other languages as well. Chinese uses the wavy dash and full-width em dash interchangeably for this purpose. In English, the tilde is often used to express ranges and model numbers in electronics, but rarely in formal grammar or in type-set documents, as a wavy dash preceding a number sometimes represents an approximation (see below).

在中文里波浪号可以作为连字符表示范围，但是这个符号是 U+FF5E “～”。

https://zh.wikipedia.org/wiki/连接号

**Comment by louisstuart96** [comment]
感谢指正。将在 https://github.com/CTeX-org/lshort-cn 这个 repo 里面修改。

**Comment by zepinglee** [comment]
建议将本 repo 标注一下 deprecated，因为我在 github 一搜 lshort-zh-cn 就到这里了
